apiVersion: v1
kind: Service
metadata:
  name: diabetes-service
  namespace: ml-platform
  labels:
    app: diabetes-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: diabetes-service
  sessionAffinity: None
